# Generated by Django 2.1.3 on 2018-12-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_auto_20181210_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maillot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maillot_picture', models.ImageField(default='static/images/maillot_pictures/maillotdefaut.jpg', upload_to='static/images/maillots_pictures/')),
            ],
        ),
    ]
