# Generated by Django 2.1.3 on 2018-12-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillot',
            name='maillot_picture',
            field=models.ImageField(default='static/images/maillots_pictures/maillotdefaut.jpg', upload_to='static/images/maillots_pictures/'),
        ),
    ]
